# Generated by Django 5.0 on 2026-04-23 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('icono', models.CharField(default='bi-tag', help_text='Clase de Bootstrap Icons', max_length=50)),
                ('orden', models.PositiveSmallIntegerField(default=0, help_text='Orden de aparición en el menú')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Plato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='platos/')),
                ('disponible', models.BooleanField(default=True, help_text='Visible en el catálogo del mesero')),
                ('tiempo_prep', models.PositiveSmallIntegerField(default=15, help_text='Tiempo estimado de preparación en minutos')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='platos', to='menu.categoria')),
            ],
            options={
                'verbose_name': 'Plato',
                'verbose_name_plural': 'Platos',
                'ordering': ['categoria__orden', 'nombre'],
            },
        ),
    ]
