# Generated by Django 5.0 on 2026-04-23 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField(unique=True, verbose_name='Número de mesa')),
                ('capacidad', models.PositiveSmallIntegerField(default=4, verbose_name='Capacidad (personas)')),
                ('piso', models.CharField(choices=[('PB', 'Planta Baja'), ('P1', 'Piso 1'), ('P2', 'Piso 2'), ('TR', 'Terraza')], default='PB', max_length=2)),
                ('estado', models.CharField(choices=[('LIBRE', 'Libre'), ('OCUPADA', 'Ocupada'), ('RESERVADA', 'Reservada'), ('MANTENIMIENTO', 'En Mantenimiento')], default='LIBRE', max_length=15)),
            ],
            options={
                'verbose_name': 'Mesa',
                'verbose_name_plural': 'Mesas',
                'ordering': ['piso', 'numero'],
            },
        ),
    ]
