# Generated by Django 5.0 on 2026-04-23 03:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
        ('mesas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('ABIERTA', 'Abierta'), ('CERRADA', 'Cerrada (Cobrada)'), ('CANCELADA', 'Cancelada')], default='ABIERTA', max_length=10)),
                ('fecha_apertura', models.DateTimeField(auto_now_add=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, help_text='Notas generales de la mesa')),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comandas', to='mesas.mesa')),
                ('mesero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comandas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comanda',
                'verbose_name_plural': 'Comandas',
                'ordering': ['-fecha_apertura'],
            },
        ),
        migrations.CreateModel(
            name='LineaComanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveSmallIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=8)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PREPARACION', 'En Preparación'), ('LISTO', 'Listo para servir'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=15)),
                ('notas_cocina', models.CharField(blank=True, help_text='Ej: Sin cebolla, término medio', max_length=255)),
                ('comanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='comandas.comanda')),
                ('plato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lineas', to='menu.plato')),
            ],
            options={
                'verbose_name': 'Línea de Comanda',
                'verbose_name_plural': 'Líneas de Comanda',
            },
        ),
    ]
